<footer class="site-footer">

    <div class="container text-center">

        <p class="mb-0">
            &copy; 2026 BookVerse Created by s4007558 Joseph Michael Saba
        </p>

    </div>

</footer>


<!-- Bootstrap JavaScript -->
<script
    src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js">
</script>


<!-- Custom JavaScript -->
<script src="/wp-fork/a2/assets/js/scripts.js"></script>

</body>

</html>